# Generated by Django 2.1.2 on 2018-10-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
