# Generated by Django 2.1.2 on 2018-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0002_joblisting_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
