# Generated by Django 2.1.2 on 2018-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0003_joblisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots/'),
        ),
    ]
