# Generated by Django 2.1.2 on 2018-11-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0004_auto_20181031_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='image',
            field=models.ImageField(blank=True, upload_to='MYKE\\media_cdn/'),
        ),
    ]
