# Generated by Django 2.1.2 on 2018-12-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_quiz_highest_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('CV', models.FileField(default='DEFAULT VALUE', upload_to='cv')),
            ],
            options={
                'db_table': 'cv',
            },
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_avatar', models.FileField(upload_to='')),
            ],
        ),
    ]
