# Generated by Django 2.1.2 on 2018-12-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_profile_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='CV',
            new_name='cv',
        ),
    ]
