# Generated by Django 2.1.2 on 2018-12-03 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='picture',
        ),
        migrations.AddField(
            model_name='cv',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='cv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
