# Generated by Django 2.1.2 on 2018-12-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20181203_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cv',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='file',
            new_name='CV',
        ),
    ]
